sudo: required

matrix:
  include:
    - language: python
      python: 3.6
      cache:
        pip: true
      install:
        - pip install django coverage coveralls
        - pip install -U channels
        - pip install -U asgi_redis
        - pip install -U django-redis
        - pip install django_extensions
        - pip install psycopg2
      before_script:
        - psql -c "create user busymanager with password 'busymanager';" -U postgres
        - psql -c 'create database busydb owner busymanager;' -U postgres
        - psql -c 'grant all privileges on database busydb to busymanager;' -U postgres
        - psql -c 'alter user busymanager createdb;' -U postgres
        - cd backend
        - python3 manage.py migrate
        - sudo redis-server
      script:
        - coverage run --branch --source="./busyback" manage.py test
      after_success:
        - coveralls
      after_script:
        - cd ..

    - language: node_js
      node_js: 8.8
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      cache:
        npm: true
        directories:
          - frontend/node_modules
      before_install:
        - export CHROME_BIN=/usr/bin/google-chrome
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - cd frontend
      install:
        - npm install
        - npm install coveralls
        - npm install -g @angular/cli
        - npm install -S angular2-websocket-service
        - npm install -S queueing-subject
      script:
        - ng test --code-coverage --watch false
        - ng e2e
      after_success:
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      after_script:
        - cd ..
